### PR TITLE
Ensures that the Search box is on top of the pane

### PR DESCRIPTION
**Pull request by deiga**
On my setup at least the Search box disappears behind some elements in the pane

### CODE REVIEW

**Comment by jaanauati** [comment]
hi @deiga, can u please share your hyper.js config so i can test this on my local? thank you!

**Comment by deiga** [comment]
Here's my hyper.js https://gist.github.com/241113c0b4aad73e2c0adb05672a7cd1

But I think it has nothing to do with my config. I just happen to have terminal output where the search box appears

**Comment by deiga** [comment]
hyper

**Comment by jaanauati** [comment]
@deiga have u also tried with zIndex=1? i tested in my local and worked

**Comment by jaanauati** [comment]
just merged and published this npm;

I don't feel confortable having these hardcoded style rules, but to be fair, there were many style props already set in this code and migrating all of them to a config file seems like a bigger effort. I created https://github.com/jaanauati/hyper-search/issues/15 to deal with this.

Thanks for helping out 🍻.

**Comment by deiga** [comment]
@jaanauati `zIndex=1` would porbably work, but I wanted to ensure that the search box keeps on top in the future too :)

**Pull request merged**
